#!/usr/bin/env python

import sqlalchemy as sa
import subprocess
import sys, os, argparse, logging

def push_from(database_name):
    print database_name

def clone_into(database_name):
    print database_name

def main(args, loglevel):
    logging.basicConfig(format="%(levelname)s: %(message)s", level=loglevel)

    base_postgres_url = os.environ.get('BASE_PG_URL')
    engine = sa.create_engine("%s/postgres" % base_postgres_url)
    conn = engine.connect()
    conn.execute("commit")

    db_name = sys.argv[1]

    #conn.execute("create database %s;" % db_name)
    result = conn.execute("select oid from pg_database where datname='%s';" % db_name)
    oid = result.fetchone()[0]
    conn.close()

    cluster_base = '/var/lib/postgresql/9.1/main'
    data_location = '%s/base/%s' % (cluster_base, oid)

    DEVNULL = open(os.devnull, 'w')
    pg_ctl = '/usr/lib/postgresql/9.1/bin/pg_ctl'

    # Stop postgres server
    logging.info("Shutting down postgres server...")
    stop_p = subprocess.Popen([pg_ctl, 'stop', '-D', cluster_base, '-m', 'fast'], stdout=DEVNULL, stderr=subprocess.STDOUT)
    stop_p.wait()

    # Clone backup into new database
    logging.info("Cloning backup from cloud...")
    clone_p = subprocess.Popen(['envdir', '/etc/wal-e.d/env', 'wal-e', 'backup-fetch', data_location, 'LATEST'], stdout=DEVNULL, stderr=subprocess.STDOUT)
    clone_p.wait()

    # Start postgres server
    logging.info("Starting postgres server...")
    start_p = subprocess.Popen([pg_ctl, 'start', '-D', cluster_base], stdout=DEVNULL, stderr=subprocess.STDOUT)
    start_p.wait()

    logging.info("Lastest backup has successfully been cloned into new database: %s" % db_name)
 
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description = "Clones a copy of a production database backup locally",)
    parser.add_argument(
                      "-p",
                      "--push",
                      help = "pushes a copy of database to the cloud",
                      metavar = "push old_database_name")
    parser.add_argument(
                      "-c",
                      "--clone",
                      help = "clones cloud backup into local database",
                      metavar = "clone new_database_name")
    args = parser.parse_args(sys.argv[1:])

    logging.basicConfig(format="%(levelname)s: %(message)s", level=logging.INFO)
    if args.push:
	push_from(args.push)
    elif args.clone:
        clone_into(args.clone)
    else:
        print "Sorry, invalid arguments"
