#!/usr/bin/env python

import sqlalchemy as sa
import subprocess
import sys, os, argparse, logging

cluster_base = '/var/lib/postgresql/9.1/main'
DEVNULL = open(os.devnull, 'w')

def get_data_location(oid):
    return '%s/base/%s' % (cluster_base, oid)

def connect_to_db():
    base_postgres_url = os.environ.get('BASE_PG_URL')
    engine = sa.create_engine("%s/postgres" % base_postgres_url)
    conn = engine.connect()
    conn.execute("commit")
    return conn

def push_from(db_name):
    conn = connect_to_db()
    result = conn.execute("select oid from pg_database where datname='%s';" % db_name)
    oid = result.fetchone()[0]
    conn.close()

    data_location = get_data_location(oid)

    # Push database into cloud backup 
    logging.info("Pushing database into cloud backup...")
    push_p = subprocess.Popen(['envdir', '/etc/wal-e.d/env', 'wal-e', 'backup-push', data_location], stdout=DEVNULL, stderr=subprocess.STDOUT)
    push_p.wait()

    logging.info("The database '%s' has successfully pushed to a cloud backup." % db_name)

def clone_into(db_name):
    conn = connect_to_db()
    #conn.execute("create database %s;" % db_name)
    result = conn.execute("select oid from pg_database where datname='%s';" % db_name)
    oid = result.fetchone()[0]
    conn.close()

    data_location = get_data_location(oid)

    pg_ctl = '/usr/lib/postgresql/9.1/bin/pg_ctl'

    # Stop postgres server
    logging.info("Shutting down postgres server...")
    stop_p = subprocess.Popen([pg_ctl, 'stop', '-D', cluster_base, '-m', 'fast'], stdout=DEVNULL, stderr=subprocess.STDOUT)
    stop_p.wait()

    # Clone backup into new database
    logging.info("Cloning backup from cloud...")
    clone_p = subprocess.Popen(['envdir', '/etc/wal-e.d/env', 'wal-e', 'backup-fetch', data_location, 'LATEST'], stdout=DEVNULL, stderr=subprocess.STDOUT)
    clone_p.wait()

    # Start postgres server
    logging.info("Starting postgres server...")
    start_p = subprocess.Popen([pg_ctl, 'start', '-D', cluster_base], stdout=DEVNULL, stderr=subprocess.STDOUT)
    start_p.wait()

    logging.info("Lastest cloud backup has successfully been cloned into new database: %s" % db_name)
 
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description = "Clones a copy of a production database backup locally",)
    parser.add_argument(
                      "-p",
                      "--push",
                      help = "pushes a copy of database to the cloud",
                      metavar = "push old_database_name")
    parser.add_argument(
                      "-c",
                      "--clone",
                      help = "clones cloud backup into local database",
                      metavar = "clone new_database_name")
    args = parser.parse_args(sys.argv[1:])

    logging.basicConfig(format="%(levelname)s: %(message)s", level=logging.INFO)
    if args.push:
	push_from(args.push)
    elif args.clone:
        clone_into(args.clone)
    else:
        print "Sorry, invalid arguments"
